/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransactionsRouteImport } from './routes/transactions'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as BalancesRouteImport } from './routes/balances'
import { Route as AccountsRouteImport } from './routes/accounts'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransactionsIndexRouteImport } from './routes/transactions.index'
import { Route as ReportsIndexRouteImport } from './routes/reports.index'
import { Route as AccountsIndexRouteImport } from './routes/accounts.index'
import { Route as TransactionsNewRouteImport } from './routes/transactions.new'
import { Route as TransactionsIdRouteImport } from './routes/transactions.$id'
import { Route as ReportsIncomeStatementRouteImport } from './routes/reports.income-statement'
import { Route as AccountsNewRouteImport } from './routes/accounts.new'
import { Route as AccountsIdRouteImport } from './routes/accounts.$id'
import { Route as TransactionsIdIndexRouteImport } from './routes/transactions.$id.index'
import { Route as AccountsIdIndexRouteImport } from './routes/accounts.$id.index'
import { Route as TransactionsIdEditRouteImport } from './routes/transactions.$id.edit'
import { Route as AccountsIdEditRouteImport } from './routes/accounts.$id.edit'

const TransactionsRoute = TransactionsRouteImport.update({
  id: '/transactions',
  path: '/transactions',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const BalancesRoute = BalancesRouteImport.update({
  id: '/balances',
  path: '/balances',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountsRoute = AccountsRouteImport.update({
  id: '/accounts',
  path: '/accounts',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransactionsIndexRoute = TransactionsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TransactionsRoute,
} as any)
const ReportsIndexRoute = ReportsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ReportsRoute,
} as any)
const AccountsIndexRoute = AccountsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountsRoute,
} as any)
const TransactionsNewRoute = TransactionsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => TransactionsRoute,
} as any)
const TransactionsIdRoute = TransactionsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => TransactionsRoute,
} as any)
const ReportsIncomeStatementRoute = ReportsIncomeStatementRouteImport.update({
  id: '/income-statement',
  path: '/income-statement',
  getParentRoute: () => ReportsRoute,
} as any)
const AccountsNewRoute = AccountsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => AccountsRoute,
} as any)
const AccountsIdRoute = AccountsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AccountsRoute,
} as any)
const TransactionsIdIndexRoute = TransactionsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TransactionsIdRoute,
} as any)
const AccountsIdIndexRoute = AccountsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AccountsIdRoute,
} as any)
const TransactionsIdEditRoute = TransactionsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => TransactionsIdRoute,
} as any)
const AccountsIdEditRoute = AccountsIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => AccountsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/balances': typeof BalancesRoute
  '/reports': typeof ReportsRouteWithChildren
  '/transactions': typeof TransactionsRouteWithChildren
  '/accounts/$id': typeof AccountsIdRouteWithChildren
  '/accounts/new': typeof AccountsNewRoute
  '/reports/income-statement': typeof ReportsIncomeStatementRoute
  '/transactions/$id': typeof TransactionsIdRouteWithChildren
  '/transactions/new': typeof TransactionsNewRoute
  '/accounts/': typeof AccountsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/transactions/': typeof TransactionsIndexRoute
  '/accounts/$id/edit': typeof AccountsIdEditRoute
  '/transactions/$id/edit': typeof TransactionsIdEditRoute
  '/accounts/$id/': typeof AccountsIdIndexRoute
  '/transactions/$id/': typeof TransactionsIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/balances': typeof BalancesRoute
  '/accounts/new': typeof AccountsNewRoute
  '/reports/income-statement': typeof ReportsIncomeStatementRoute
  '/transactions/new': typeof TransactionsNewRoute
  '/accounts': typeof AccountsIndexRoute
  '/reports': typeof ReportsIndexRoute
  '/transactions': typeof TransactionsIndexRoute
  '/accounts/$id/edit': typeof AccountsIdEditRoute
  '/transactions/$id/edit': typeof TransactionsIdEditRoute
  '/accounts/$id': typeof AccountsIdIndexRoute
  '/transactions/$id': typeof TransactionsIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/accounts': typeof AccountsRouteWithChildren
  '/balances': typeof BalancesRoute
  '/reports': typeof ReportsRouteWithChildren
  '/transactions': typeof TransactionsRouteWithChildren
  '/accounts/$id': typeof AccountsIdRouteWithChildren
  '/accounts/new': typeof AccountsNewRoute
  '/reports/income-statement': typeof ReportsIncomeStatementRoute
  '/transactions/$id': typeof TransactionsIdRouteWithChildren
  '/transactions/new': typeof TransactionsNewRoute
  '/accounts/': typeof AccountsIndexRoute
  '/reports/': typeof ReportsIndexRoute
  '/transactions/': typeof TransactionsIndexRoute
  '/accounts/$id/edit': typeof AccountsIdEditRoute
  '/transactions/$id/edit': typeof TransactionsIdEditRoute
  '/accounts/$id/': typeof AccountsIdIndexRoute
  '/transactions/$id/': typeof TransactionsIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accounts'
    | '/balances'
    | '/reports'
    | '/transactions'
    | '/accounts/$id'
    | '/accounts/new'
    | '/reports/income-statement'
    | '/transactions/$id'
    | '/transactions/new'
    | '/accounts/'
    | '/reports/'
    | '/transactions/'
    | '/accounts/$id/edit'
    | '/transactions/$id/edit'
    | '/accounts/$id/'
    | '/transactions/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/balances'
    | '/accounts/new'
    | '/reports/income-statement'
    | '/transactions/new'
    | '/accounts'
    | '/reports'
    | '/transactions'
    | '/accounts/$id/edit'
    | '/transactions/$id/edit'
    | '/accounts/$id'
    | '/transactions/$id'
  id:
    | '__root__'
    | '/'
    | '/accounts'
    | '/balances'
    | '/reports'
    | '/transactions'
    | '/accounts/$id'
    | '/accounts/new'
    | '/reports/income-statement'
    | '/transactions/$id'
    | '/transactions/new'
    | '/accounts/'
    | '/reports/'
    | '/transactions/'
    | '/accounts/$id/edit'
    | '/transactions/$id/edit'
    | '/accounts/$id/'
    | '/transactions/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountsRoute: typeof AccountsRouteWithChildren
  BalancesRoute: typeof BalancesRoute
  ReportsRoute: typeof ReportsRouteWithChildren
  TransactionsRoute: typeof TransactionsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transactions': {
      id: '/transactions'
      path: '/transactions'
      fullPath: '/transactions'
      preLoaderRoute: typeof TransactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/balances': {
      id: '/balances'
      path: '/balances'
      fullPath: '/balances'
      preLoaderRoute: typeof BalancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accounts': {
      id: '/accounts'
      path: '/accounts'
      fullPath: '/accounts'
      preLoaderRoute: typeof AccountsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transactions/': {
      id: '/transactions/'
      path: '/'
      fullPath: '/transactions/'
      preLoaderRoute: typeof TransactionsIndexRouteImport
      parentRoute: typeof TransactionsRoute
    }
    '/reports/': {
      id: '/reports/'
      path: '/'
      fullPath: '/reports/'
      preLoaderRoute: typeof ReportsIndexRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/accounts/': {
      id: '/accounts/'
      path: '/'
      fullPath: '/accounts/'
      preLoaderRoute: typeof AccountsIndexRouteImport
      parentRoute: typeof AccountsRoute
    }
    '/transactions/new': {
      id: '/transactions/new'
      path: '/new'
      fullPath: '/transactions/new'
      preLoaderRoute: typeof TransactionsNewRouteImport
      parentRoute: typeof TransactionsRoute
    }
    '/transactions/$id': {
      id: '/transactions/$id'
      path: '/$id'
      fullPath: '/transactions/$id'
      preLoaderRoute: typeof TransactionsIdRouteImport
      parentRoute: typeof TransactionsRoute
    }
    '/reports/income-statement': {
      id: '/reports/income-statement'
      path: '/income-statement'
      fullPath: '/reports/income-statement'
      preLoaderRoute: typeof ReportsIncomeStatementRouteImport
      parentRoute: typeof ReportsRoute
    }
    '/accounts/new': {
      id: '/accounts/new'
      path: '/new'
      fullPath: '/accounts/new'
      preLoaderRoute: typeof AccountsNewRouteImport
      parentRoute: typeof AccountsRoute
    }
    '/accounts/$id': {
      id: '/accounts/$id'
      path: '/$id'
      fullPath: '/accounts/$id'
      preLoaderRoute: typeof AccountsIdRouteImport
      parentRoute: typeof AccountsRoute
    }
    '/transactions/$id/': {
      id: '/transactions/$id/'
      path: '/'
      fullPath: '/transactions/$id/'
      preLoaderRoute: typeof TransactionsIdIndexRouteImport
      parentRoute: typeof TransactionsIdRoute
    }
    '/accounts/$id/': {
      id: '/accounts/$id/'
      path: '/'
      fullPath: '/accounts/$id/'
      preLoaderRoute: typeof AccountsIdIndexRouteImport
      parentRoute: typeof AccountsIdRoute
    }
    '/transactions/$id/edit': {
      id: '/transactions/$id/edit'
      path: '/edit'
      fullPath: '/transactions/$id/edit'
      preLoaderRoute: typeof TransactionsIdEditRouteImport
      parentRoute: typeof TransactionsIdRoute
    }
    '/accounts/$id/edit': {
      id: '/accounts/$id/edit'
      path: '/edit'
      fullPath: '/accounts/$id/edit'
      preLoaderRoute: typeof AccountsIdEditRouteImport
      parentRoute: typeof AccountsIdRoute
    }
  }
}

interface AccountsIdRouteChildren {
  AccountsIdEditRoute: typeof AccountsIdEditRoute
  AccountsIdIndexRoute: typeof AccountsIdIndexRoute
}

const AccountsIdRouteChildren: AccountsIdRouteChildren = {
  AccountsIdEditRoute: AccountsIdEditRoute,
  AccountsIdIndexRoute: AccountsIdIndexRoute,
}

const AccountsIdRouteWithChildren = AccountsIdRoute._addFileChildren(
  AccountsIdRouteChildren,
)

interface AccountsRouteChildren {
  AccountsIdRoute: typeof AccountsIdRouteWithChildren
  AccountsNewRoute: typeof AccountsNewRoute
  AccountsIndexRoute: typeof AccountsIndexRoute
}

const AccountsRouteChildren: AccountsRouteChildren = {
  AccountsIdRoute: AccountsIdRouteWithChildren,
  AccountsNewRoute: AccountsNewRoute,
  AccountsIndexRoute: AccountsIndexRoute,
}

const AccountsRouteWithChildren = AccountsRoute._addFileChildren(
  AccountsRouteChildren,
)

interface ReportsRouteChildren {
  ReportsIncomeStatementRoute: typeof ReportsIncomeStatementRoute
  ReportsIndexRoute: typeof ReportsIndexRoute
}

const ReportsRouteChildren: ReportsRouteChildren = {
  ReportsIncomeStatementRoute: ReportsIncomeStatementRoute,
  ReportsIndexRoute: ReportsIndexRoute,
}

const ReportsRouteWithChildren =
  ReportsRoute._addFileChildren(ReportsRouteChildren)

interface TransactionsIdRouteChildren {
  TransactionsIdEditRoute: typeof TransactionsIdEditRoute
  TransactionsIdIndexRoute: typeof TransactionsIdIndexRoute
}

const TransactionsIdRouteChildren: TransactionsIdRouteChildren = {
  TransactionsIdEditRoute: TransactionsIdEditRoute,
  TransactionsIdIndexRoute: TransactionsIdIndexRoute,
}

const TransactionsIdRouteWithChildren = TransactionsIdRoute._addFileChildren(
  TransactionsIdRouteChildren,
)

interface TransactionsRouteChildren {
  TransactionsIdRoute: typeof TransactionsIdRouteWithChildren
  TransactionsNewRoute: typeof TransactionsNewRoute
  TransactionsIndexRoute: typeof TransactionsIndexRoute
}

const TransactionsRouteChildren: TransactionsRouteChildren = {
  TransactionsIdRoute: TransactionsIdRouteWithChildren,
  TransactionsNewRoute: TransactionsNewRoute,
  TransactionsIndexRoute: TransactionsIndexRoute,
}

const TransactionsRouteWithChildren = TransactionsRoute._addFileChildren(
  TransactionsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountsRoute: AccountsRouteWithChildren,
  BalancesRoute: BalancesRoute,
  ReportsRoute: ReportsRouteWithChildren,
  TransactionsRoute: TransactionsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
